### ISSUE TITLE
[Question] Time for extracting laser data.

### ISSUE THREAD

**Issue by chrockey** [DapengFeng/waymo-toolkit#2]
Hi, thank you for sharing your toolkit.

I tried to use your toolkit but it was slower than I expected.
It took 64 secs per frame to extract laser data with single TITAN RTX GPU. 
Is it the same speed with yours?

By the way, thank you again for your work!

**Comment by DapengFeng** [comment]
> Hi, thank you for sharing your toolkit.
> 
> I tried to use your toolkit but it was slower than I expected.
> It took 64 secs per frame to extract laser data with single TITAN RTX GPU.
> Is it the same speed with yours?
> 
> By the way, thank you again for your work!

I tested it on the CPU @ 2.70GHz server before, with a speed performance of 1~2 secs per frame.

**Comment by chrockey** [comment]
Ah, thank you for your reply.
It might be related to CPU of my server. I gonna check it out.

thank you!
