### ISSUE TITLE
.pb convert to txt

### ISSUE THREAD

**Issue by williamhyin** [DapengFeng/waymo-toolkit#3]
Hi, How can i convert outputed label.pt to 2d boudingbox prediction txt?

Thanks

**Comment by DapengFeng** [comment]
You can refer to the following code to parse the annotations from the label.pb, and save them in any format you want.
https://github.com/DapengFeng/waymo-toolkit/blob/005b3a5de804e3933271cdb1d7bd90b62fa82ed7/waymo_toolkit/viewer/viewer_2d.py#L121-L122
https://github.com/DapengFeng/waymo-toolkit/blob/005b3a5de804e3933271cdb1d7bd90b62fa82ed7/waymo_toolkit/viewer/viewer_2d.py#L130-L133
https://github.com/DapengFeng/waymo-toolkit/blob/005b3a5de804e3933271cdb1d7bd90b62fa82ed7/waymo_toolkit/viewer/viewer_2d.py#L29-L46
